class BathroomOrganizer {
    public static void main(String args[]) {
        String mountingType = "Wall Mount";
        String roomType = "Bathroom, Bedroom, Living Room";
        String shelfType = "Hanging Shelf";
        String shape = "Rectangular";
        String style = "Modern";
        String finishType = "Powder Coated";
        String furnitureFinish = "Powder-coated";
        String shelfBracketShape = "Flat";
        String colour = "(A) Black";
        String brand = "Plantex";
        String manufacturer = "Plantex E-commerce Private Limited, Ahmedabad";
        String modelNumber = "APS-2003-Black";
        String manufacturerPartNumber = "APS-2003-Black";
        String setName = "Single";
        String includedComponents = "2-Adhesive Stickers, Bathroom Shelf";
        String countryOfOrigin = "India";
        String bedType = "Self adhesive shelf";
        String packerContact = "Plantex E-Commerce Private Limited, Ahmedabad, Customer Care - 756 756 7500, Email - cs@plantex.in";
        String importerContact = "Plantex E-Commerce Private Limited, Ahmedabad, Customer Care - 756 756 7500, Email - cs@plantex.in";
        String manufacturerContact = "Plot no. 5, Road no. 1, Kathwada GIDC, Ahmedabad, Customer Care - 756 756 7500";
        String productFeatures = "Durable";
        String recommendedUses = "Living Room, Bed Room, Bath Room";
        String productCare = "Wipe with cloth periodically to make it last longer";
        String installationType = "Wall Mount";
        String assemblyInstructions = "No assembly required";
        String woodType = "Steel";
        String asin = "B0B3J7Q14R";
        int numberOfShelves = 1;
        int numberOfItems = 1;
        int unitCount = 1;
        double weightCapacityKg = 5;
        double itemWeight = 0.49;
        double shelfThickness = 11.5;
        int price = 198;
        int bestSellerRankHomeImprovement = 43;
        int bestSellerRankBathroomShelves = 4;
        String itemDimensions = "28 x 10 x 11.5 Centimeters";
        System.out.println("Mounting Type: " + mountingType);
        System.out.println("Room Type: " + roomType);
        System.out.println("Shelf Type: " + shelfType);
        System.out.println("Shape: " + shape);
        System.out.println("Style: " + style);
        System.out.println("Finish Type: " + finishType);
        System.out.println("Furniture Finish: " + furnitureFinish);
        System.out.println("Shelf Bracket Shape: " + shelfBracketShape);
        System.out.println("Colour: " + colour);
        System.out.println("Brand: " + brand);
        System.out.println("Manufacturer: " + manufacturer);
        System.out.println("Model Number: " + modelNumber);
        System.out.println("Manufacturer Part Number: " + manufacturerPartNumber);
        System.out.println("Set Name: " + setName);
        System.out.println("Included Components: " + includedComponents);
        System.out.println("Country of Origin: " + countryOfOrigin);
        System.out.println("Bed Type: " + bedType);
        System.out.println("ASIN: " + asin);
        System.out.println("Packer Contact: " + packerContact);
        System.out.println("Importer Contact: " + importerContact);
        System.out.println("Manufacturer Contact: " + manufacturerContact);
        System.out.println("Product Features: " + productFeatures);
        System.out.println("Recommended Uses: " + recommendedUses);
        System.out.println("Product Care: " + productCare);
        System.out.println("Installation Type: " + installationType);
        System.out.println("Assembly Instructions: " + assemblyInstructions);
        System.out.println("Item Dimensions: " + itemDimensions);
        System.out.println("Shelf Thickness: " + shelfThickness + " cm");
        System.out.println("Weight Capacity: " + weightCapacityKg + " kg");
        System.out.println("Item Weight: " + itemWeight + " kg");
        System.out.println("Number of Shelves: " + numberOfShelves);
        System.out.println("Number of Items: " + numberOfItems);
        System.out.println("Unit Count: " + unitCount);
        System.out.println("Best Seller Rank (Home Improvement): #" + bestSellerRankHomeImprovement);
        System.out.println("Best Seller Rank (Bathroom Shelves): #" + bestSellerRankBathroomShelves);
        System.out.println("Price: " + price);
    }
}