class DishWasherCloth {
    public static void main(String args[]) {
        String brand = "VOLTURI";
        String countryOfOrigin = "India";
        String setName = "10";
        String modelName = "VOLTURI-NSDWC";
        String manufacturer = "VOLTURI, Surat, Gujarat - 395004. Email: customercare@volturi.in. Mobile: +91-2613189860";
        String manufacturerPartNumber = "VOLTURI-NSDWC";
        String modelNumber = "VOLTURI-NSDWC";
        String ageRange = "Adult";
        String includedComponents = "10 x Double-Layer Non Scratch Dish Wash Cloth";
        String packerContact = "VOLTURI, Surat, Gujarat - 395004. Email: customercare@volturi.in. Mobile: +91-2613189857";
        String manufacturerContact = "VOLTURI, Surat, Gujarat - 395004. Email: customercare@volturi.in. Mobile: +91-2613189860";
        String itemTypeName = "Non Scratch Dish Wash Cloth";
        String asin = "B0D3LXD8JM";
        String customerReviews = "4.1 out of 5 stars (2,138 reviews)";
        String colour = "Silver";
        String productStyle = "Pack of 10";
        String pattern = "Mesh";
        String shape = "Square";
        String enclosureMaterial = "Stainless Steel Mesh";
        String productCare = "Hand wash only. Avoid high heat. Air dry. Do not use brushes or abrasive cleaning supplies.";
        String fabricType = "Stainless Steel Mesh";
        String itemDimensions = "20L x 20W Centimeters";
        String size = "Double Layer - Pack of 10";
        String towelFormType = "Kitchen Cloth";
        String specialFeatures = "Disposable, Reusable";
        int numberOfItems = 10;
        int fabricWeight = 80;
        int unitCount = 10;
        int itemWeight = 80;
        int bestSellerRankHomeImprovement = 113;
        int bestSellerRankScrubsSponges = 10;
        int price = 199;
        System.out.println("Brand: " + brand);
        System.out.println("Country of Origin: " + countryOfOrigin);
        System.out.println("Set Name: " + setName);
        System.out.println("Model Name: " + modelName);
        System.out.println("Manufacturer: " + manufacturer);
        System.out.println("Manufacturer Part Number: " + manufacturerPartNumber);
        System.out.println("Model Number: " + modelNumber);
        System.out.println("Age Range: " + ageRange);
        System.out.println("Included Components: " + includedComponents);
        System.out.println("Item Type Name: " + itemTypeName);
        System.out.println("ASIN: " + asin);
        System.out.println("Customer Reviews: " + customerReviews);
        System.out.println("Packer Contact: " + packerContact);
        System.out.println("Manufacturer Contact: " + manufacturerContact);
        System.out.println("Colour: " + colour);
        System.out.println("Product Style: " + productStyle);
        System.out.println("Pattern: " + pattern);
        System.out.println("Shape: " + shape);
        System.out.println("Enclosure Material: " + enclosureMaterial);
        System.out.println("Fabric Type: " + fabricType);
        System.out.println("Product Care: " + productCare);
        System.out.println("Item Dimensions: " + itemDimensions);
        System.out.println("Size: " + size);
        System.out.println("Towel Form Type: " + towelFormType);
        System.out.println("Special Features: " + specialFeatures);
        System.out.println("Item Weight: " + itemWeight + " grams");
        System.out.println("Number of Items: " + numberOfItems);
        System.out.println("Unit Count: " + unitCount);
        System.out.println("Best Seller Rank (Home Improvement): #" + bestSellerRankHomeImprovement);
        System.out.println("Best Seller Rank (Scrubs & Sponges): #" + bestSellerRankScrubsSponges);
        System.out.println("Price: " + price);
    }
}