class Facewash {
    public static void main(String args[]) {
        String scent = "Fresh";
        String skinType = "All";
        String productBenefits = "Cleansing, Hydrating";
        String additionalFeatures = "Hydrating";
        String itemForm = "Gel";
        String specialIngredients = "Hyaluronic Acid";
        String targetUseBodyPart = "Face";
        String recommendedUses = "Cleaning, Hydrating";
        String packageType = "Tube";
        String materialFeatures = "Dermatologist Tested";
        String materialTypeFree = "Oil Free";
        String colour = "Clear";
        String brand = "L'Oreal Paris";
        String ageRange = "Adult";
        String countryOfOrigin = "Indonesia";
        String manufacturerPartNumber = "DERAF100";
        String modelNumber = "DERAF100";
        String manufacturerContact = "PT. YASULOR INDONESIA, Cikarang Utara, Bekasi, Indonesia";
        String packerContact = "PT. YASULOR INDONESIA, Cikarang Utara, Bekasi, Indonesia";
        String importerContact = "Loreal India Pvt. Ltd., Mumbai, Maharashtra, India";
        String itemTypeName = "Facewash";
        String itemDimensions = "6.1 x 3.1 x 16 Centimeters";
        int itemWeight = 110;
        int itemPackageQuantity = 1;
        int numberOfItems = 1;
        double unitCount = 100.0;
        double netContentWeight = 100.0;
        double netContentVolume = 100.0;
        String packageTypeName = "Tube";
        int price = 430;
        System.out.println("Scent: " + scent);
        System.out.println("Skin Type: " + skinType);
        System.out.println("Product Benefits: " + productBenefits);
        System.out.println("Additional Features: " + additionalFeatures);
        System.out.println("Item Form: " + itemForm);
        System.out.println("Special Ingredients: " + specialIngredients);
        System.out.println("Target Use Body Part: " + targetUseBodyPart);
        System.out.println("Recommended Uses: " + recommendedUses);
        System.out.println("Package Type: " + packageType);
        System.out.println("Material Features: " + materialFeatures);
        System.out.println("Material Type Free: " + materialTypeFree);
        System.out.println("Colour: " + colour);
        System.out.println("Brand: " + brand);
        System.out.println("Age Range: " + ageRange);
        System.out.println("Country of Origin: " + countryOfOrigin);
        System.out.println("Manufacturer Part Number: " + manufacturerPartNumber);
        System.out.println("Model Number: " + modelNumber);
        System.out.println("Manufacturer Contact: " + manufacturerContact);
        System.out.println("Packer Contact: " + packerContact);
        System.out.println("Importer Contact: " + importerContact);
        System.out.println("Item Type Name: " + itemTypeName);
        System.out.println("Item Dimensions: " + itemDimensions);
        System.out.println("Item Weight: " + itemWeight + " Grams");
        System.out.println("Item Package Quantity: " + itemPackageQuantity);
        System.out.println("Number of Items: " + numberOfItems);
        System.out.println("Unit Count: " + unitCount + " Milliliters");
        System.out.println("Net Content Weight: " + netContentWeight + " Grams");
        System.out.println("Net Content Volume: " + netContentVolume + " Millilitres");
        System.out.println("Package Type Name: " + packageTypeName);
        System.out.println("Price: " + price);
    }
}