class GalaBroom {
    public static void main(String args[]) {
        String brand = "Gala";
        String recommendedUses = "Floor Cleaning, Dusting";
        String surfaceRecommendation = "Hard Floor";
        String includedComponents = "1 Modular No Dust Broom Handle with Broom";
        String modelNumber = "164152";
        String globalTradeId = "08901663004430";
        String manufacturer = "Freudenberg Household Pvt Ltd, India, A-707, O2 Galleria, Mulund (West), Mumbai – 400080, +91 9167607774";
        String manufacturerPartNumber = "164152";
        String manufacturerContact = "Freudenberg Household Pvt Ltd, India, A-707, O2 Galleria, Mulund (West), Mumbai – 400080, +91 9167607774";
        String countryOfOrigin = "India";
        String warranty = "No Warranty";
        String itemTypeName = "Brooms";
        String packerContact = "Freudenberg Household Pvt Ltd, India, A-707, O2 Galleria, Mulund (West), Mumbai – 400080, +91 9167607774";
        String asin = "B081QG2SL1";
        String itemDimensions = "11W x 64.5H Centimeters";
        String bristleMaterial = "Nylon";
        String handleMaterial = "Plastic";
        String enclosureMaterial = "Nylon";
        String bristleType = "Flagged Bristle";
        String colour = "Blue";
        String productStyle = "Traditional";
        String productFeatures = "Lightweight";
        int unitCount = 1;
        int itemWeight = 280;
        int price = 180;
        int bestSellerRankHomeImprovement = 126;
        int bestSellerRankBrooms = 4;
        System.out.println("Brand: " + brand);
        System.out.println("Recommended Uses: " + recommendedUses);
        System.out.println("Surface Recommendation: " + surfaceRecommendation);
        System.out.println("Included Components: " + includedComponents);
        System.out.println("Model Number: " + modelNumber);
        System.out.println("Global Trade ID: " + globalTradeId);
        System.out.println("Manufacturer: " + manufacturer);
        System.out.println("Manufacturer Part Number: " + manufacturerPartNumber);
        System.out.println("Manufacturer Contact: " + manufacturerContact);
        System.out.println("Country of Origin: " + countryOfOrigin);
        System.out.println("Warranty: " + warranty);
        System.out.println("Item Type Name: " + itemTypeName);
        System.out.println("Packer Contact: " + packerContact);
        System.out.println("ASIN: " + asin);
        System.out.println("Item Dimensions: " + itemDimensions);
        System.out.println("Bristle Material: " + bristleMaterial);
        System.out.println("Handle Material: " + handleMaterial);
        System.out.println("Enclosure Material: " + enclosureMaterial);
        System.out.println("Bristle Type: " + bristleType);
        System.out.println("Colour: " + colour);
        System.out.println("Product Style: " + productStyle);
        System.out.println("Product Features: " + productFeatures);
        System.out.println("Unit Count: " + unitCount);
        System.out.println("Item Weight: " + itemWeight + " grams");
        System.out.println("Best Seller Rank (Home Improvement): #" + bestSellerRankHomeImprovement);
        System.out.println("Best Seller Rank (Brooms): #" + bestSellerRankBrooms);
        System.out.println("Price: " + price);
    }
}