class Microwave {
    public static void main(String args[]) {
        String heatingMode = "Solo";
        String fuelType = "Electric";
        String installationType = "Freestanding";
        String specialFeatures = "Auto Cook, Child Lock, Defrost, Timer, Turntable";
        String timerFunction = "Timer Function Available";
        String doorOrientation = "Left";
        String lockType = "Child Lock Available";
        String brand = "LG";
        String manufacturer = "LG";
        String modelName = "MS2043BP";
        String manufacturerPartNumber = "MS2043BP";
        String modelNumber = "MS2043BP";
        String countryOfOrigin = "India";
        String itemTypeName = "Microwave Oven";
        String warrantyDescription = "1 year Manufacturer Warranty";
        String manufacturerContact = "LG Service India";
        String importerContact = "LG";
        String packerContact = "LG";
        String includedComponents = "1 Set";
        String defrostSystemType = "Defrost";
        String size = "20 L";
        String itemDimensions = "32D x 45.5W x 25.2H Centimeters";
        String colour = "Black";
        String finishType = "Polished";
        String materialType = "Steel";
        int wattage = 700;
        int voltage = 230;
        int frequency = 50;
        int unitCount = 1;
        double itemWeight = 2645.55;
        int capacity = 20;
        int price = 8900;
        System.out.println("Heating Mode: " + heatingMode);
        System.out.println("Fuel Type: " + fuelType);
        System.out.println("Installation Type: " + installationType);
        System.out.println("Special Features: " + specialFeatures);
        System.out.println("Timer Function: " + timerFunction);
        System.out.println("Door Orientation: " + doorOrientation);
        System.out.println("Lock Type: " + lockType);
        System.out.println("Brand Name: " + brand);
        System.out.println("Manufacturer: " + manufacturer);
        System.out.println("Model Name: " + modelName);
        System.out.println("Manufacturer Part Number: " + manufacturerPartNumber);
        System.out.println("Model Number: " + modelNumber);
        System.out.println("Country Of Origin: " + countryOfOrigin);
        System.out.println("Item Type Name: " + itemTypeName);
        System.out.println("Warranty Description: " + warrantyDescription);
        System.out.println("Included Components: " + includedComponents);
        System.out.println("Defrost System Type: " + defrostSystemType);
        System.out.println("Size: " + size);
        System.out.println("Item Dimensions: " + itemDimensions);
        System.out.println("Item Weight: " + itemWeight + " Grams");
        System.out.println("Colour: " + colour);
        System.out.println("Finish Type: " + finishType);
        System.out.println("Material Type: " + materialType);
        System.out.println("Wattage: " + wattage + " Watts");
        System.out.println("Voltage: " + voltage + " Volts");
        System.out.println("Frequency: " + frequency + " Hz");
        System.out.println("Unit Count: " + unitCount);
        System.out.println("Capacity: " + capacity + " Litres");
        System.out.println("Price: ₹" + price);
    }
}