class NeckPillow {
    public static void main(String args[]) {
        String brand = "Shuddh Kaaya";
        String ageRange = "Adult";
        String coinVariety = "Neck Pillow";
        String modelName = "Grey Big Eye Neck-1";
        String manufacturer = "Vartin Enterprises";
        String modelNumber = "Grey Big Eye Neck-1";
        String colour = "Grey";
        String shape = "Semicircular";
        String pattern = "Abstract";
        String itemTypeName = "Travel Neck Pillow";
        String countryOfOrigin = "India";
        String fillMaterial = "Polyester";
        String enclosureMaterial = "Polyester";
        String productCare = "Hand Wash Only";
        String materialFeatures = "Organic";
        String materialFree = "PVC Free";
        String fabricType = "Velvet";
        String size = "Free Size";
        String dimensions = "32L x 10W x 32H Centimeters";
        String itemDimensionsLW = "32L x 10W Centimeters";
        String specialFeatures = "Lightweight";
        String targetBodyPart = "Head, Neck, Shoulders";
        String firmness = "Soft";
        String recommendedUses = "Travelling";
        String specificUses = "Neck Pain";
        String asin = "B0H1HC5JW3";
        int numberOfPieces = 1;
        int unitCount = 1;
        int itemWeight = 200;
        int price = 180;
        int bestSellerRankBags = 6381;
        int bestSellerRankTravelPillows = 123;
        System.out.println("Age Range: " + ageRange);
        System.out.println("Coin Variety: " + coinVariety);
        System.out.println("Model Name: " + modelName);
        System.out.println("Manufacturer: " + manufacturer);
        System.out.println("Model Number: " + modelNumber);
        System.out.println("Colour: " + colour);
        System.out.println("Shape: " + shape);
        System.out.println("Pattern: " + pattern);
        System.out.println("Item Type: " + itemTypeName);
        System.out.println("Country of Origin: " + countryOfOrigin);
        System.out.println("Fill Material: " + fillMaterial);
        System.out.println("Enclosure Material: " + enclosureMaterial);
        System.out.println("Product Care: " + productCare);
        System.out.println("Material Features: " + materialFeatures);
        System.out.println("Material Free: " + materialFree);
        System.out.println("Fabric Type: " + fabricType);
        System.out.println("Size: " + size);
        System.out.println("Dimensions: " + dimensions);
        System.out.println("Item Dimensions (L x W): " + itemDimensionsLW);
        System.out.println("Item Weight: " + itemWeight + " grams");
        System.out.println("Special Features: " + specialFeatures);
        System.out.println("Target Body Part: " + targetBodyPart);
        System.out.println("Firmness: " + firmness);
        System.out.println("Recommended Uses: " + recommendedUses);
        System.out.println("Specific Uses: " + specificUses);
        System.out.println("Number of Pieces: " + numberOfPieces);
        System.out.println("Unit Count: " + unitCount);
        System.out.println("ASIN: " + asin);
        System.out.println("Best Seller Rank (Bags): #" + bestSellerRankBags);
        System.out.println("Best Seller Rank (Travel Pillows): #" + bestSellerRankTravelPillows);
        System.out.println("Price: " + price);
    }
}