class RectangularPhotoFrame {
    public static void main(String args[]) {
        String brand = "BEHOMA";
        String colour = "Golden";
        String itemShape = "Rectangular";
        String finishType = "EPL/Plating";
        String productStyle = "Palm Tree";
        String theme = "Decoration";
        String occasion = "Anniversary, Birthday, Mother's Day, Sweet Sentiments";
        String pattern = "Palm Tree";
        String frameMaterial = "Aluminium";
        String productCare = "Wipe With Wet Cloth";
        String backMaterialType = "Metal";
        String itemDimensions = "17.5L x 15.5W Centimeters";
        String size = "4*6";
        String mountingType = "Tabletop, Wall Mount";
        String specialFeatures = "Home Décor";
        String orientation = "Vertical";
        String recommendedUses = "Displaying photos/artwork, home decor, gifting, tabletop or wall mounting";
        String frameType = "Tabletop";
        String countryOfOrigin = "India";
        String manufacturer = "Behoma Private Limited";
        String partNumber = "FR5031S";
        String itemTypeName = "Aluminium";
        String packerContact = "Behoma Pvt Ltd, contact@.in, 8800020788, Pincode-110065";
        String asin = "B0DQXSXSM8";
        int numberOfItems = 1;
        int unitCount = 1;
        double itemWeight = 0.34;
        int bestSellerRankHomeKitchen = 158381;
        int bestSellerRankFrames = 1512;
        int price = 899;
        System.out.println("Brand: " + brand);
        System.out.println("Colour: " + colour);
        System.out.println("Item Shape: " + itemShape);
        System.out.println("Finish Type: " + finishType);
        System.out.println("Product Style: " + productStyle);
        System.out.println("Theme: " + theme);
        System.out.println("Occasion: " + occasion);
        System.out.println("Pattern: " + pattern);
        System.out.println("Frame Material: " + frameMaterial);
        System.out.println("Product Care: " + productCare);
        System.out.println("Back Material Type: " + backMaterialType);
        System.out.println("Item Dimensions: " + itemDimensions);
        System.out.println("Item Weight: " + itemWeight + " kg");
        System.out.println("Size: " + size);
        System.out.println("Mounting Type: " + mountingType);
        System.out.println("Special Features: " + specialFeatures);
        System.out.println("Orientation: " + orientation);
        System.out.println("Recommended Uses: " + recommendedUses);
        System.out.println("Frame Type: " + frameType);
        System.out.println("Country of Origin: " + countryOfOrigin);
        System.out.println("Manufacturer: " + manufacturer);
        System.out.println("Part Number: " + partNumber);
        System.out.println("Item Type Name: " + itemTypeName);
        System.out.println("Packer Contact: " + packerContact);
        System.out.println("ASIN: " + asin);
        System.out.println("Number of Items: " + numberOfItems);
        System.out.println("Unit Count: " + unitCount);
        System.out.println("Best Seller Rank (Home & Kitchen): #" + bestSellerRankHomeKitchen);
        System.out.println("Best Seller Rank (Frames): #" + bestSellerRankFrames);
        System.out.println("Price: " + price);
    }
}