class Sunscreen {
    public static void main(String args[]) {
        String scent = "Lemon";
        String productBenefits = "Ultra-Violet Protection";
        String spf = "50 Sun Protection Factor (SPF)";
        String skinType = "Oily";
        String waterResistance = "Water Resistant";
        String itemForm = "Cream";
        String colour = "Yellow";
        String additionalFeatures = "Non-Greasy, Non-Oily, Enriched with Kaolin Clay, Lemon Extracts, and Vitamin E";
        String skinTone = "All";
        String activeIngredients = "SPF 50 PA+++, Kaolin Clay, Lemon Extract, Vitamin E";
        String materialFeatures = "SPF 50, UVA/UVB Protection, Oil Control, Vitamin C, Vitamin E";
        String materialTypeFree = "Paraben Free";
        String recommendedUses = "Outdoor activities, daily wear, beach/pool use";
        String brand = "Lacto Calamine";
        String ageRange = "Adult";
        String manufacturer = "Alaina Healthcare Pvt. Ltd., Baddi - 174103";
        String manufacturerPartNumber = "8904026643864";
        String modelNumber = "8904026643864";
        String manufacturerContact = "Alaina Healthcare Pvt. Ltd., Baddi - 174103";
        String packerContact = "Alaina Healthcare Pvt. Ltd.";
        String countryOfOrigin = "India";
        String itemTypeName = "Sunscreen";
        String asin = "B0CTTQQ8BT";
        String itemDimensions = "6.4 x 4.1 x 14.8 Centimeters";
        int itemWeight = 100;
        int numberOfItems = 1;
        double unitCount = 100.0;
        int bestSellerRankBeauty = 3109;
        int bestSellerRankSunscreen = 149;
        int price = 199;
        System.out.println("Scent: " + scent);
        System.out.println("Product Benefits: " + productBenefits);
        System.out.println("SPF: " + spf);
        System.out.println("Skin Type: " + skinType);
        System.out.println("Water Resistance Level: " + waterResistance);
        System.out.println("Item Form: " + itemForm);
        System.out.println("Colour: " + colour);
        System.out.println("Additional Features: " + additionalFeatures);
        System.out.println("Skin Tone: " + skinTone);
        System.out.println("Active Ingredients: " + activeIngredients);
        System.out.println("Material Features: " + materialFeatures);
        System.out.println("Material Type Free: " + materialTypeFree);
        System.out.println("Recommended Uses: " + recommendedUses);
        System.out.println("Brand: " + brand);
        System.out.println("Age Range: " + ageRange);
        System.out.println("Manufacturer: " + manufacturer);
        System.out.println("Manufacturer Part Number: " + manufacturerPartNumber);
        System.out.println("Model Number: " + modelNumber);
        System.out.println("Manufacturer Contact: " + manufacturerContact);
        System.out.println("Packer Contact: " + packerContact);
        System.out.println("Country of Origin: " + countryOfOrigin);
        System.out.println("Item Type Name: " + itemTypeName);
        System.out.println("ASIN: " + asin);
        System.out.println("Item Dimensions: " + itemDimensions);
        System.out.println("Item Weight: " + itemWeight + " Grams");
        System.out.println("Number of Items: " + numberOfItems);
        System.out.println("Unit Count: " + unitCount + " Grams");
        System.out.println("Best Seller Rank (Beauty): #" + bestSellerRankBeauty);
        System.out.println("Best Seller Rank (Sunscreen): #" + bestSellerRankSunscreen);
        System.out.println("Price: ₹" + price);
    }
}